# Generated by Django 4.2.5 on 2023-11-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_products_product_handle_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='handle',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
