# Generated by Django 4.2.5 on 2023-11-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_alter_product_handle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.AlterField(
            model_name='product',
            name='handle',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
